### ISSUE TITLE
Sometimes text_to_speech.speech_to_strip does not work ( maybe when text is too long and Japanese )

### ISSUE THREAD

**Issue by araigumaG** [technisculpt/blender-text-to-speech#4]
method to reproduce: 
1. input "いろはにほへとちりぬるをわかよた"(16 letters, 32 bytes) in text_to_speech.string_field, then push "Text to Speech".
2. push "Convert Selected to Text Strip" with selecting the new sound strip (named "いろはにほへとちりぬるをわかよたyyyyMMddhhmms" lacking the last letter of "hhmmss" ), yet **none of text strip spawns**.
3. taking same process with another input, "いろはにほへとちりぬるをわかよ", then spawns the strip is named "いろはにほへとちりぬるをわかよyyyyMMddhhmmss"( including the information about date and time perfectly like "yyyyMMddhhmmss" )

my hypothesis: 
When a sound strip is made ( "sound_strip_from_text()" works ), the function makes the name of the strip by cutting the text off and making it shorter to fit in the name of a strip.
In this situation, the function seems not to use the byte length but the number of letters. If it cause the difference between strip name and filename, the problem would happen on remove_deleted_strips()@operators.py.

I'm sorry to say this, but I haven't been still able to give you more detailed information and any proposal for fix.

Thank you.

**Comment by technisculpt** [comment]
thanks i'll look into this soon when i get some time

**Comment by araigumaG** [comment]
Thank you for replying!
I wrote a sloppy fix for this issue, e60d53b10470dfa8fdbfb307b173911592df9fcd .
I have no idea about you are tolerant enough to accept this fix. Is it better to make PR?

**Comment by technisculpt** [comment]
👍 @araigumaG awesome thankyou for this, it looks good in passing. I will spend some time very soon testing in some other languages and linux/windows/mac

Are you windows10?

If i use your approach we can do a PR, i'll keep you posted

**Comment by technisculpt** [comment]
hi @araigumaG thanks for bringing this to my attention. I have gone with a slightly different approach, but same idea. It should work now.

Because the strings to be truncated can potentially be very long and there might be many (entire movie scripts via closed caption files) i implemented a binary search to truncate the filename length and added some other checks,[ it can be viewed here](https://github.com/technisculpt/blender-text-to-speech/blob/58ef5e2423301ce97d5f56ffd898803303755806/Text%20to%20Speech/text_to_sound.py):
